[build]
  # The command to build your Next.js application
  command = "npm install --force && npm audit fix --force && npm run build"

  # The directory where the build output will be located
  publish = ".next"
